const productsBath = [
  {
    id: 'bathbam01',
    detailimage: process.env.PUBLIC_URL+'/images/detail_01.jpg',
    image: process.env.PUBLIC_URL+'/images/pro01_off_bam.png',
    material: 'vegan',
    name: '인터갈락밤',
    title: '배쓰밤',
    price: 17000,
    descimageTop: process.env.PUBLIC_URL+'/images/detail_01_desc01.jpg',
    descimageMid: process.env.PUBLIC_URL+'/images/detail_01_desc02.jpg',
    descimageBottom: process.env.PUBLIC_URL+'/images/detail_01_desc03.jpg'
  },
  {
    id: 'bathbam02',
    detailimage: process.env.PUBLIC_URL+'/images/detail_02.jpg',
    image: process.env.PUBLIC_URL+'/images/pro02_off_bam.png',
    material: 'vegan',
    name: '가디스',
    title: '배쓰밤',
    price: 20000,
    descimageTop: process.env.PUBLIC_URL+'/images/detail_02_desc01.jpg',
    descimageMid: process.env.PUBLIC_URL+'/images/detail_02_desc02.jpg',
    descimageBottom: process.env.PUBLIC_URL+'/images/detail_02_desc03.jpg'
  },
  {
    id: 'bathbam03',
    detailimage: process.env.PUBLIC_URL+'/images/detail_03.jpg',
    image: process.env.PUBLIC_URL+'/images/pro03_off_bam.png',
    material: 'vegan',
    name: '사쿠라',
    title: '배쓰밤',
    price: 13000,
    descimageTop: process.env.PUBLIC_URL+'/images/detail_03_desc01.jpg',
    descimageMid: process.env.PUBLIC_URL+'/images/detail_03_desc02.jpg',
    descimageBottom: process.env.PUBLIC_URL+'/images/detail_03_desc03.jpg'
  },
  {
    id: 'bathbam04',
    detailimage: process.env.PUBLIC_URL+'/images/detail_03.jpg',
    image: process.env.PUBLIC_URL+'/images/pro04_off_bam.png',
    material: 'vegan',
    name: '트와일라잇',
    title: '배쓰밤',
    price: 14000,
    descimageTop: process.env.PUBLIC_URL+'/images/detail_03_desc01.jpg',
    descimageMid: process.env.PUBLIC_URL+'/images/detail_03_desc02.jpg',
    descimageBottom: process.env.PUBLIC_URL+'/images/detail_03_desc03.jpg'
  },
  {
    id: 'bathbam05',
    detailimage: process.env.PUBLIC_URL+'/images/detail_03.jpg',
    image: process.env.PUBLIC_URL+'/images/pro05_off_bam.png',
    material: 'vegan',
    name: '루비 카인드 오브 러브',
    title: '배쓰밤',
    price: 18000,
    descimageTop: process.env.PUBLIC_URL+'/images/detail_03_desc01.jpg',
    descimageMid: process.env.PUBLIC_URL+'/images/detail_03_desc02.jpg',
    descimageBottom: process.env.PUBLIC_URL+'/images/detail_03_desc03.jpg'
  },
  {
    id: 'bathbam06',
    detailimage: process.env.PUBLIC_URL+'/images/detail_03.jpg',
    image: process.env.PUBLIC_URL+'/images/pro06_off_bam.png',
    material: 'vegan',
    name: '딥 슬립',
    title: '배쓰밤',
    price: 20000,
    descimageTop: process.env.PUBLIC_URL+'/images/detail_03_desc01.jpg',
    descimageMid: process.env.PUBLIC_URL+'/images/detail_03_desc02.jpg',
    descimageBottom: process.env.PUBLIC_URL+'/images/detail_03_desc03.jpg' 
  },
  {
    id: 'bathbam07',
    detailimage: process.env.PUBLIC_URL+'/images/detail_03.jpg',
    image: process.env.PUBLIC_URL+'/images/pro07_off_bam.png',
    material: 'vegan',
    name: '빅 블루',
    title: '배쓰밤',
    price: 14000,
    descimageTop: process.env.PUBLIC_URL+'/images/detail_03_desc01.jpg',
    descimageMid: process.env.PUBLIC_URL+'/images/detail_03_desc02.jpg',
    descimageBottom: process.env.PUBLIC_URL+'/images/detail_03_desc03.jpg' 
  },
  {
    id: 'bathbam08',
    detailimage: process.env.PUBLIC_URL+'/images/detail_03.jpg',
    image: process.env.PUBLIC_URL+'/images/pro08_off_bam.png',
    material: 'vegan',
    name: '이클 베이비 봇',
    title: '배쓰밤',
    price: 8000,
    descimageTop: process.env.PUBLIC_URL+'/images/detail_03_desc01.jpg',
    descimageMid: process.env.PUBLIC_URL+'/images/detail_03_desc02.jpg',
    descimageBottom: process.env.PUBLIC_URL+'/images/detail_03_desc03.jpg'  
  },
  {
    id: 'bathbam09',
    detailimage: process.env.PUBLIC_URL+'/images/detail_03.jpg',
    image: process.env.PUBLIC_URL+'/images/pro09_off_bam.png',
    material: 'vegan',
    name: '드래곤스 에그',
    title: '배쓰밤',
    price: 14000,
    descimageTop: process.env.PUBLIC_URL+'/images/detail_03_desc01.jpg',
    descimageMid: process.env.PUBLIC_URL+'/images/detail_03_desc02.jpg',
    descimageBottom: process.env.PUBLIC_URL+'/images/detail_03_desc03.jpg'  
  },
  {
    id: 'bathbam10',
    detailimage: process.env.PUBLIC_URL+'/images/detail_03.jpg',
    image: process.env.PUBLIC_URL+'/images/pro10_off_bam.png',
    material: 'vegan',
    name: '피치',
    title: '배쓰밤',
    price: 17000,
    descimageTop: process.env.PUBLIC_URL+'/images/detail_03_desc01.jpg',
    descimageMid: process.env.PUBLIC_URL+'/images/detail_03_desc02.jpg',
    descimageBottom: process.env.PUBLIC_URL+'/images/detail_03_desc03.jpg'  
  },
  {
    id: 'bathbam11',
    detailimage: process.env.PUBLIC_URL+'/images/detail_03.jpg',
    image: process.env.PUBLIC_URL+'/images/pro11_off_bam.png',
    material: 'vegan',
    name: '버터볼',
    title: '배쓰밤',
    price: 8000,
    descimageTop: process.env.PUBLIC_URL+'/images/detail_03_desc01.jpg',
    descimageMid: process.env.PUBLIC_URL+'/images/detail_03_desc02.jpg',
    descimageBottom: process.env.PUBLIC_URL+'/images/detail_03_desc03.jpg'   
  },
  {
    id: 'bathbam12',
    detailimage: process.env.PUBLIC_URL+'/images/detail_03.jpg',
    image: process.env.PUBLIC_URL+'/images/pro12_off_bam.png',
    material: 'vegan',
    name: '아보배쓰',
    title: '배쓰밤',
    price: 13000,
    descimageTop: process.env.PUBLIC_URL+'/images/detail_03_desc01.jpg',
    descimageMid: process.env.PUBLIC_URL+'/images/detail_03_desc02.jpg',
    descimageBottom: process.env.PUBLIC_URL+'/images/detail_03_desc03.jpg'  
  },
  {
    id: 'bathbam13',
    detailimage: process.env.PUBLIC_URL+'/images/detail_03.jpg',
    image: process.env.PUBLIC_URL+'/images/pro13_off_bam.png',
    material: 'vegan',
    name: '마쉬멜로우 월드',
    title: '배쓰밤',
    price: 18000,
    descimageTop: process.env.PUBLIC_URL+'/images/detail_03_desc01.jpg',
    descimageMid: process.env.PUBLIC_URL+'/images/detail_03_desc02.jpg',
    descimageBottom: process.env.PUBLIC_URL+'/images/detail_03_desc03.jpg'  
  },
  {
    id: 'bathbam14',
    detailimage: process.env.PUBLIC_URL+'/images/detail_03.jpg',
    image: process.env.PUBLIC_URL+'/images/pro14_off_bam.png',
    material: 'vegan',
    name: '멜리진',
    title: '배쓰밤',
    price: 19000,
    descimageTop: process.env.PUBLIC_URL+'/images/detail_03_desc01.jpg',
    descimageMid: process.env.PUBLIC_URL+'/images/detail_03_desc02.jpg',
    descimageBottom: process.env.PUBLIC_URL+'/images/detail_03_desc03.jpg'  
  },
  {
    id: 'bathbam15',
    detailimage: process.env.PUBLIC_URL+'/images/detail_03.jpg',
    image: process.env.PUBLIC_URL+'/images/pro15_off_bam.png',
    material: 'vegan',
    name: '티스티 토스티',
    title: '배쓰밤',
    price: 14000,
    descimageTop: process.env.PUBLIC_URL+'/images/detail_03_desc01.jpg',
    descimageMid: process.env.PUBLIC_URL+'/images/detail_03_desc02.jpg',
    descimageBottom: process.env.PUBLIC_URL+'/images/detail_03_desc03.jpg'   
  },
  {
    id: 'bathbam16',
    detailimage: process.env.PUBLIC_URL+'/images/detail_03.jpg',
    image: process.env.PUBLIC_URL+'/images/pro16_off_bam.png',
    material: 'vegan',
    name: '블랙로즈',
    title: '배쓰밤',
    price: 18000,
    descimageTop: process.env.PUBLIC_URL+'/images/detail_03_desc01.jpg',
    descimageMid: process.env.PUBLIC_URL+'/images/detail_03_desc02.jpg',
    descimageBottom: process.env.PUBLIC_URL+'/images/detail_03_desc03.jpg'  
  }
]

export default productsBath